module.exports = {
  User: require('./User'),
  Role: require('./Role'),
  Permission: require('./Permission'),
  Incident: require('./Incident'),
  Announcement: require('./Announcement'),
  Event: require('./Event'),
  EventRegistration: require('./EventRegistration'),
  Donation: require('./Donation'),
  Document: require('./Document'),
  Notification: require('./Notification'),
  Feedback: require('./Feedback'),
  Hazard: require('./Hazard'),
  Chatbot: require('./Chatbot'),
  Hotline: require('./Hotline'),
  Setting: require('./Setting'),
  Log: require('./Log'),
  Archive: require('./Archive'),
};
